openapi: 3.0.1
info:
  title: Content based router example
  description: Content based router example using news service
  version: 1.0.0
servers:
  - url: http://localhost:8290/dynamicEndpoint

paths:
  /route:
    get:
      summary: 'get sample'
      responses:
        default:
          description: Default response
          content:
            application/json:
              examples:
                default:
                  value: "{}"